var _aa=null;var _ba=null;var _ca=false;var _da=1*24*60*60*1000;var _ea=1*12*60*60*1000;var _fa=['http://dmp.adform.net/serving/cookie/match/?party=1099&cid={YKUID}'];var _ga=['http://hades.srvtrck.com/v1/profile?action=create&ykuid={YKUID}'];var _ha=['http://hades.srvtrck.com/v1/profile?action=opt_out&ykuid={YKUID}'];var _ia=['http://hades.srvtrck.com/v1/profile?action=opt_in&ykuid={YKUID}'];function log(va){if(_ca){console.log(va);}}
function errorLogger(wa){wa="Hades Server:"+wa+" URL: "+document.location.href+" Agent: "+navigator.userAgent;if(_ca){console.log(wa);}
img=document.createElement("img");img.src='https://r.srvtrck.com/v1/log?message='+encodeURIComponent(wa);};function _ja(xa,ya,za){for(i=0;i<xa.length;i++){xa[i]=xa[i].replace(ya,za);}
return xa;};function cookiesEnabled(){try{var Aa=false;document.cookie="testcookie";Aa=(document.cookie.indexOf("testcookie")!=-1)?true:false;return(Aa);}catch(err){log("cookies are disabled "+err);return false;}};function _ka(){if(location.protocol==='https:'){_ja(_ga,'http','https');_ja(_fa,'http','https');_ja(_ha,'http','https');_ja(_ia,'http','https');}};function _la(){var Ba=Math.random().toString(36).substring(2,15)+Math.random().toString(36).substring(2,15);log("generated uuid: "+Ba);return Ba;};var _ma=false;if('localStorage' in window){try{window.localStorage.setItem('_tmptest','tmpval');window.localStorage.removeItem('_tmptest');_ma=true;}
catch(BogusQuotaExceededErrorOnIos5){}};if(_ma){try{if(window.localStorage){_aa=window.localStorage;_ba='localStorage';}}
catch(E3){}}
else if('globalStorage' in window){try{if(window.globalStorage){if(window.location.hostname=='localhost'){_aa=window.globalStorage['localhost.localdomain'];}
else{_aa=window.globalStorage[window.location.hostname];}
_ba='globalStorage';}}
catch(E4){}};if(_ba==null&&cookiesEnabled()){_ba="cookieStorage";}
function _na(){var Ca=_oa("uuid");if(Ca==null){Ca=_la();_pa("uuid",Ca);_pa("opt_out","false");}
return Ca;};function _qa(Da,Ea,Fa){var d=new Date();d.setTime(d.getTime()+(Fa*24*60*60*1000));var Ga="expires="+d.toUTCString();document.cookie=Da+"="+Ea+"; "+Ga;};function _ra(Ha){var Ia=Ha+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(Ia)==0)return c.substring(Ia.length,c.length);}
return null;};function _sa(Ja){if(_ba=='localStorage'||_ba=='globalStorage'){try{var Ka=_aa.removeItem(Ja);return Ka;}catch(err){errorLogger('delete from local storage failed, key: '+Ja+" ,msg:"+err);}}else if(_ba=='cookieStorage'){try{var Ka=_qa(Ja,'',-10);return Ka;}catch(err){errorLogger('delete from cookie failed, key: '+Ja+" ,msg:"+err);return null;}}};function _oa(La){if(_ba=='localStorage'||_ba=='globalStorage'){try{var Ma=_aa.getItem(La);return Ma;}catch(err){errorLogger('get from localstorage failed, key: '+La+" ,msg:"+err);return null;}}else if(_ba=='cookieStorage'){try{var Ma=_ra(La);return Ma;}catch(err){errorLogger('get from cookie failed, key: '+La+" ,msg:"+err);return null;}}};function _pa(Na,Oa){if(_ba=='localStorage'||_ba=='globalStorage'){try{_aa.setItem(Na,Oa);}catch(err){errorLogger('set to local storage failed, key: '+Na+" ,msg:"+err);}}else if(_ba=='cookieStorage'){try{_qa(Na,Oa,365);}catch(err){errorLogger('set to cookie failed, key: '+Na+" ,msg:"+err);}}};function _ta(Pa){for(var i=0;i<Pa.length;i++){var Qa=Pa[i];obj=document.createElement("img");obj.src=Qa;log("syncing: "+Qa);}};function getQueryVariable(Ra){var Sa=window.location.search.substring(1);var Ta=Sa.split('&');for(var i=0;i<Ta.length;i++){var Ua=Ta[i].split('=');if(decodeURIComponent(Ua[0])==Ra){return decodeURIComponent(Ua[1]);}}
log('Query variable %s not found',Ra);};function _ua(){var Va=window.location.href;if(Va.indexOf('ykuid')!=-1){var Wa=getQueryVariable('ykuid');var Xa=_oa("uuid");if(Xa==null){_pa("uuid",Wa);_pa("opt_out","false");}else{_sa('last_sync_partner');_sa('last_sync');}}};function init(){if(!('postMessage' in window)){errorLogger('postMessage not supported');return;}
_ka();_ua();try{var Ya="true"==_oa("opt_out");var Za=_na();var $a={};$a.uuid=Za;$a.optOut=Ya;$a.action='setUuidYK';var ab='*';log("sending yuid: "+Za);var m=JSON.stringify($a);window.parent.postMessage(m,ab);if(Ya){return;}
var bb=_oa("last_sync_partner");bb=bb==null?null:new Date(Date.parse(bb));if(bb==null||((new Date().getTime()-bb.getTime())>_da)){var cb=_ja(_fa,'{YKUID}',_na());_ta(cb);_pa("last_sync_partner",new Date());}
bb=_oa("last_sync");bb=bb==null?null:new Date(Date.parse(bb));if(bb==null||((new Date().getTime()-bb.getTime())>_ea)){var cb=_ja(_ga,'{YKUID}',_na());_ta(cb);_pa("last_sync",new Date());}}catch(err){errorLogger('failed in receiveMessage : '+err.message);}};try{init();}catch(err){errorLogger('failed in load : '+err.message);}